services:
  # PostgreSQL - Banco de dados relacional
  postgres:
    image: postgres:15-alpine
    container_name: biblioteca-postgres
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - biblioteca-network

  # pgAdmin - Interface de gerenciamento PostgreSQL
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: biblioteca-pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pedro@biblioteca.com
#      PGADMIN_DEFAULT_PASSWORD: admin123
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    networks:
#      - biblioteca-network
#    depends_on:
#      - postgres

  # Adminer - Interface web leve (alternativa ao pgAdmin)
  adminer:
    image: adminer:latest
    container_name: biblioteca-adminer
    ports:
      - "8085:8080"
    networks:
      - biblioteca-network
    depends_on:
      - postgres

  # MinIO - Armazenamento de objetos
  minio:
    image: minio/minio:latest
    container_name: biblioteca-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console Web
    volumes:
      - minio-data:/data
    networks:
      - biblioteca-network

volumes:
  postgres-data:
  pgadmin-data:
  minio-data:

networks:
  biblioteca-network:
    driver: bridge