
services:
  # PostgreSQL - Banco de dados relacional
  postgres:
    image: postgres:15-alpine
    container_name: biblioteca-postgres
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - biblioteca-network

  # MinIO - Armazenamento de objetos
  minio:
    image: minio/minio:latest
    container_name: biblioteca-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console Web
    volumes:
      - minio-data:/data
    networks:
      - biblioteca-network

volumes:
  postgres-data:
  minio-data:

networks:
  biblioteca-network:
    driver: bridge